# ==========================
# Configuração do sistema de Login
# ==========================

geral:
  enabled: true
  prefix: "&3&lNew&bLogin &7» "
  min-password-length: 4
  max-password-length: 32

  # Bloqueia comandos antes do jogador logar
  block-commands-before-login: true

  # Comandos permitidos antes do login (sem / e em minúsculas)
  allowed-commands-before-login:
    - "login"
    - "logar"
    - "register"
    - "registro"

  # Comandos que NÃO devem aparecer no console (sem / e em minúsculas)
  hide-from-console:
    - "login"
    - "register"
    - "resetsenha"

on-join:
  teleport-to-spawn: true     # Teleportar para o spawn ao entrar (se definido)

timeout:
  seconds: 60
  message: "&cVocê foi kickado por inatividade ao logar!"

mensagens:
  only-player: "&cApenas jogadores podem usar este comando."
  not-initialized: "&cSistema de login não inicializado."
  already-logged: "&eVocê já está logado."
  not-logged: "&cVocê precisa estar logado para isso."
  login-success: "&aLogin efetuado com sucesso!"
  login-fail: "&cSenha incorreta!"
  usage-login: "&eUso correto: /login <senha>"
  usage-register: "&eUso correto: /register <senha>"
  already-registered: "&cVocê já está registrado."
  register-success: "&aRegistrado com sucesso! Agora use /login <senha>."
  password-too-short: "&cA senha deve ter pelo menos &f%min% &ccaracteres."
  password-too-long: "&cA senha deve ter no máximo &f%max% &ccaracteres."
  reset-success: "&aSenha de %player% foi resetada."
  reset-fail: "&cJogador %player% não encontrado ou não registrado."
  new-password: "&eNova senha: &f%senha%"
  joined-register: "&eBem-vindo! Use &a/register <senha>&e para se registrar."
  joined-login: "&eVocê já é registrado. Use &a/login <senha>&e para entrar."
  must-login: "&cVocê precisa se logar primeiro! Use /login ou /register."

# spawn: será preenchido por /newlogin setspawn
# saida: será preenchido por /newlogin setsaida
